# The ovnconfig config file. Used by master processes in hypershift hostedcluster.
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovnkube-config
  namespace: {{.HostedClusterNamespace}}
  annotations:
    network.operator.openshift.io/cluster-name:  {{.ManagementClusterName}}
data:
  ovnkube.conf:   |-
    [default]
    mtu="{{.MTU}}"
    {{- if .RoutableMTU }}
    routable-mtu="{{.RoutableMTU}}"
    {{- end }}
    cluster-subnets="{{.OVN_cidr}}"
    enable-lflow-cache=true
    lflow-cache-limit-kb=1048576

    [kubernetes]
    service-cidrs="{{.OVN_service_cidr}}"
    ovn-config-namespace="openshift-ovn-kubernetes"
    cacert="/hosted-ca/ca.crt"
    apiserver="{{.K8S_LOCAL_APISERVER}}"
    host-network-namespace="openshift-host-network"
{{- if .OVNHybridOverlayEnable }}
    no-hostsubnet-nodes="kubernetes.io/os=windows"
{{- end  }}
    platform-type="{{.PlatformType}}"
    dns-service-namespace="openshift-dns"
    dns-service-name="dns-default"

    [ovnkubernetesfeature]
    enable-egress-ip=true
    enable-egress-firewall=true
    enable-egress-qos=true
    enable-egress-service=true
{{- if .ReachabilityTotalTimeoutSeconds }}
    egressip-reachability-total-timeout={{.ReachabilityTotalTimeoutSeconds}}
{{- end }}
{{- if .ReachabilityNodePort }}
    egressip-node-healthcheck-port={{.ReachabilityNodePort}}
{{- end }}
{{- if .OVN_MULTI_NETWORK_POLICY_ENABLE }}
    enable-multi-networkpolicy=true
{{- end }}
{{- if .OVN_ADMIN_NETWORK_POLICY_ENABLE }}
    enable-admin-network-policy=true
{{- end }}
    enable-multi-external-gateway=true

    [gateway]
    mode={{.OVN_GATEWAY_MODE}}
    nodeport=true
{{- if (index . "V4InternalMasqueradeSubnet")}}
    v4-masquerade-subnet="{{.V4InternalMasqueradeSubnet}}"
{{- end }}
{{- if (index . "V6InternalMasqueradeSubnet")}}
    v6-masquerade-subnet="{{.V6InternalMasqueradeSubnet}}"
{{- end }}


    [logging]
    libovsdblogfile=/var/log/ovnkube/libovsdb.log
    logfile-maxsize=100
    logfile-maxbackups=5
    logfile-maxage=0

{{- if .OVNHybridOverlayEnable }}
    [hybridoverlay]
    enabled=true
    {{- if .OVNHybridOverlayNetCIDR }}
    cluster-subnets="{{.OVNHybridOverlayNetCIDR}}"
    {{- end }}
    {{- if .OVNHybridOverlayVXLANPort}}
    hybrid-overlay-vxlan-port="{{.OVNHybridOverlayVXLANPort}}"
    {{- end }}
{{- end  }}
