apiVersion: v1
kind: Service
metadata:
  labels:
    app: ovnkube-controller
  name: ovn-kubernetes-controller
  namespace: openshift-ovn-kubernetes
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ovn-master-metrics-cert
spec:
  selector:
    app: ovnkube-control-plane
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: metrics
      port: 9106
      protocol: TCP
      targetPort: 9106
  sessionAffinity: None
  type: ClusterIP
