---
# service to expose the ovn-master pod
# at present ovn-master is limited to a single instance so
# when the cluster has multiple masters we can get to the
# ovn-master via this service.
apiVersion: v1
kind: Service
metadata:
  name: ovnkube-db
  namespace: openshift-ovn-kubernetes
spec:
  selector:
    app: ovnkube-master
  ports:
  - name: north
    port: {{.OVN_NB_PORT}}
    protocol: TCP
    targetPort: {{.OVN_NB_PORT}}
  - name: south
    port: {{.OVN_SB_PORT}}
    protocol: TCP
    targetPort: {{.OVN_SB_PORT}}
  sessionAffinity: None
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ovnkube-controller
  name: ovn-kubernetes-controller
  namespace: openshift-ovn-kubernetes
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ovn-master-metrics-cert
spec:
  selector:
    app: ovnkube-master
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: metrics
      port: 9102
      protocol: TCP
      targetPort: 9102
  sessionAffinity: None
  type: ClusterIP
