apiVersion: v1
kind: ConfigMap
metadata:
  name: ovnkube-script-lib-control-plane
  namespace: openshift-ovn-kubernetes
  annotations:
    kubernetes.io/description: |
      This is a script used by the ovn-kubernetes daemonset
    release.openshift.io/version: "{{.ReleaseVersion}}"
data:
  ovnkube-lib.sh: |-
    #!/bin/bash
    
    start-ovnkube-control-plane()
    {
      local metrics_port=$1
      
      ovn_v4_join_subnet_opt=
      if [[ "{{.V4JoinSubnet}}" != "" ]]; then
        ovn_v4_join_subnet_opt="--gateway-v4-join-subnet {{.V4JoinSubnet}}"
      fi
      ovn_v6_join_subnet_opt=
      if [[ "{{.V6JoinSubnet}}" != "" ]]; then
        ovn_v6_join_subnet_opt="--gateway-v6-join-subnet {{.V6JoinSubnet}}"
      fi
      
      ovn_v4_transit_switch_subnet_opt=
      if [[ "{{.V4TransitSwitchSubnet}}" != "" ]]; then
        ovn_v4_transit_switch_subnet_opt="--cluster-manager-v4-transit-switch-subnet {{.V4TransitSwitchSubnet}}"
      fi
      ovn_v6_transit_switch_subnet_opt=
      if [[ "{{.V6TransitSwitchSubnet}}" != "" ]]; then
        ovn_v6_transit_switch_subnet_opt="--cluster-manager-v6-transit-switch-subnet {{.V6TransitSwitchSubnet}}"
      fi
    
      admin_network_policy_enabled_flag=
      if [[ "{{.OVN_ADMIN_NETWORK_POLICY_ENABLE}}" == "true" ]]; then
        admin_network_policy_enabled_flag="--enable-admin-network-policy"
      fi
    
      dns_name_resolver_enabled_flag=
      if [[ "{{.DNS_NAME_RESOLVER_ENABLE}}" == "true" ]]; then
        dns_name_resolver_enabled_flag="--enable-dns-name-resolver"
      fi
    
      multi_network_enabled_flag=
      if [[ "{{.OVN_MULTI_NETWORK_ENABLE}}" == "true" ]]; then
        multi_network_enabled_flag="--enable-multi-network"
      fi
      
      echo "I$(date "+%m%d %H:%M:%S.%N") - ovnkube-control-plane - start ovnkube --init-cluster-manager ${K8S_NODE}"
      exec /usr/bin/ovnkube \
      --enable-interconnect \
      --init-cluster-manager "${K8S_NODE}" \
      --config-file=/run/ovnkube-config/ovnkube.conf \
      --loglevel "${OVN_KUBE_LOG_LEVEL}" \
      --metrics-bind-address "127.0.0.1:${metrics_port}" \
      --metrics-enable-pprof \
      --metrics-enable-config-duration \
      ${ovn_v4_join_subnet_opt} \
      ${ovn_v6_join_subnet_opt} \
      ${ovn_v4_transit_switch_subnet_opt} \
      ${ovn_v6_transit_switch_subnet_opt} \
      ${admin_network_policy_enabled_flag} \
      ${dns_name_resolver_enabled_flag} \
      ${multi_network_enabled_flag}
    }